# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         FreeMind-Convert
version:      0.01
version_from: lib/FreeMind/Convert.pm
installdirs:  site
requires:
    Class::Accessor:               0.01
    XML::Simple:                   0.01

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
